language: objective-c
before_install:
    - brew update
    - brew install xctool
script: xctool -project LighterViewControllerDemo.xcodeproj -scheme LighterViewControllerDemoTest2 -sdk iphonesimulator  test
